name: spider
description: A small dart command-line tool for generating dart references of assets from the assets folder.
version: 4.2.3

repository: https://github.com/BirjuVachhani/spider
homepage: https://github.com/BirjuVachhani/spider
issue_tracker: https://github.com/BirjuVachhani/spider/issues
documentation: https://birjuvachhani.github.io/spider/

environment:
  sdk: ">=3.9.0 <4.0.0"

platforms:
  linux:
  windows:
  macos:

dependencies:
  path: ^1.9.1
  yaml: ^3.1.3
  args: ^2.7.0
  dart_style: ^3.1.2
  logging: ^1.3.0
  watcher: ^1.1.4
  http: ^1.5.0
  html: ^0.15.6
  sprintf: ^7.0.0
  meta: ^1.17.0
  ansicolor: ^2.0.3
  collection: ^1.19.1

dev_dependencies:
  # 2.4.5 doesn't work with logging.
  build_runner: ^2.9.0
  build_version: ^2.1.3
  test: ^1.26.3
  lints: ^6.0.0
  mockito: ^5.5.1

executables:
  spider: spider

scripts: scripts.yaml
